config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  devise_for :admin_users, ActiveAdmin::Devise.config
  resources :achievements
  default_url_options host: ENV.fetch('HOST', 'localhost:3000')

  ActiveAdmin.routes(self)
  root to: 'pages#home'

  resources :tasks do
    member do
      patch :toggle_status
    end
    collection do
      get 'filter'
    end
  end
  resources :calender, only: [:index] do
    collection do
      get :week
      get :month
    end
  end
  resources :achievements
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    if user.admin?
      can :manage, :all
    else
      can :read, :all
      cannot %i[create update destroy], Task
    end
  end
end

app/models/achievement.rb
class Achievement < ApplicationRecord
end

app/models/achievement_user.rb
class AchievementUser < ApplicationRecord
  has_many :achievements
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :recoverable, :rememberable, :validatable
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :recoverable, :rememberable, :validatable

  def self.ransackable_attributes(_auth_object = nil)
    %w[created_at email encrypted_password id id_value remember_created_at reset_password_sent_at reset_password_token updated_at]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/group.rb
class Group < ApplicationRecord
  def self.ransackable_attributes(_auth_object = nil)
    %w[created_at desc id name size updated_at]
  end
end

app/models/streak.rb
class Streak < ApplicationRecord
  belongs_to :user

  def self.create(type)
    Streak.find_or_create_by(user_id: current_user.id, created_at: Date.today, types: type)
  end
end

app/models/task.rb
class Task < ApplicationRecord
  belongs_to :user

  validates :title, :text, :types, :due_date, :points, presence: true
  validates :points, numericality: { only_integer: true, greater_than: 0 }
  validates :types, inclusion: { in: %w[Task Exam] }
  validates :due_date, date: { after: proc { Date.today }, message: 'must be in the future' }

  has_defaults status: 'upcoming'
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
         :confirmable, :lockable, :timeoutable, :trackable

  has_many :tasks, dependent: :destroy
  has_many :achievement_users, dependent: :destroy

  enum roles: %w[user admin]

  def self.ransackable_attributes(_auth_object = nil)
    %w[created_at email encrypted_password id id_value remember_created_at reset_password_sent_at reset_password_token roles updated_at]
  end
end

app/models/user_group.rb
class UserGroup < ApplicationRecord
end

app/controllers/achievements_controller.rb
class AchievementsController < ApplicationController
  before_action :authenticate_user!

  def index
    @user_achievements, @achievements = load_achievements
    @streak_daily, @streak_weekly = load_streak
  end

  private

  def load_achievements
    [AchievementUser.where(user_id: current_user.id), Achievement.all]
  end

  def load_streak
    [streak_daily, streak_weekly]
  end

  def streak_daily
    dates = Streak.where(user_id: current_user.id).order(:created_at).pluck(:created_at).map(&:to_date)
    return 0 if dates.empty?

    dates.chunk_while { |i, j| i + 1 == j }.map(&:size).max
  end

  def streak_weekly
    dates = Streak.where(user_id: current_user.id).order(:created_at).pluck(:created_at).map(&:to_date)
    return 0 if dates.empty?

    dates.chunk_while { |i, j| i + 1 == j }.map(&:first).map(&:beginning_of_week).uniq.size
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/calender_controller.rb
class CalenderController < ApplicationController
  before_action :authenticate_user!

  def index
    load_tasks
    load_tasks_limit
  end

  def month
    load_tasks('month')
    load_tasks_limit
  end

  def week
    load_tasks('week')
  end

  private

  def load_tasks_limit
    @load_tasks_limit ||= Task.where(types: 'Exam', user_id: current_user.id).order(created_at: :desc).limit(10)
  end

  def load_tasks(view = 'month')
    @load_tasks ||= Task.where(due_date: date_range(view), types: 'Exam', user_id: current_user.id).order(created_at: :desc)
  end

  def date_range(view)
    if %w[month all].include?(view)
      start_date = params[:start_date].present? ? params[:start_date].to_date.beginning_of_month : Date.today.beginning_of_month
      end_date = start_date.end_of_month
    elsif view == 'week'
      start_date = params[:start_date].present? ? params[:start_date].to_date.beginning_of_week : Date.today.beginning_of_week
      end_date = start_date.end_of_week
    end

    start_date..end_date
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home; end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :authenticate_user!

  def new
    if can? :create, Task
      build_task
    else
      head :forbidden
    end
  end

  def create
    if can? :create, Task
      build_task
      save_task(event: 'task:created', form: 'new')
    else
      head :forbidden
    end
  end

  def edit
    if can? :update, Task
      load_task
      build_task
    else
      head :forbidden
    end
  end

  def update
    if can? :update, Task
      load_task
      build_task
      save_task(form: 'edit')
    else
      head :forbidden
    end
  end

  def show
    load_task
  end

  def index
    load_tasks
  end

  def destroy
    if can? :destroy, Task
      load_task
      if @load_task.destroy
        up.layer.emit('task:destroyed')
        redirect_to tasks_path
      else
        redirect_to @load_task, alert: 'Could not delete task'
      end
    else
      head :forbidden
    end
  end

  def filter
    if %w[upcoming completed].include?(params[:status].to_s)
      @load_tasks = task_scope.where(status: params[:status]).to_a
    elsif %w[past_due].include?(params[:status].to_s)
      @load_tasks = task_scope.where('due_date < ?', Time.now).where(status: 'upcoming').to_a
    end
    render :index
  end

  private

  def load_tasks
    @load_tasks ||= task_scope.order(due_date: :asc).to_a
  end

  def task_scope
    Task.where(user_id: current_user.id)
  end

  def load_task
    @load_task ||= task_scope.find(params[:id])
  rescue ActiveRecord::RecordNotFound
    render :index, alert: 'Task not found'
  end

  def build_task
    @load_task ||= task_scope.build
    @load_task.attributes = task_attributes
  end

  def save_task(form:, event: nil)
    if up.validate?
      @load_task.valid?
      render form
    elsif @load_task.save
      up.layer.emit(event) if event
      redirect_to @load_task, notice: 'Task saved successfully'
    else
      render form, status: :bad_request
    end
  end

  def task_attributes
    if (attrs = params[:task])
      attrs.permit(:title, :text, :types, :status, :due_date, :points)
    else
      {}
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/calendar_helper.rb
module CalendarHelper
  def event_position(due_date)
    calendar_start_time = 6 * 60
    calendar_end_time = 20 * 60
    fractions_per_minute = 350.0 / (calendar_end_time - calendar_start_time)

    event_start_minutes = (due_date.hour * 60) + due_date.min - 80
    event_end_minutes = (due_date.hour * 60) + due_date.min - 20

    grid_row_start = ((event_start_minutes - calendar_start_time) * fractions_per_minute).round + 1
    grid_row_span = ((event_end_minutes - event_start_minutes) * fractions_per_minute).round

    [grid_row_start, grid_row_span]
  end
end

app/views/active_storage/blobs/_blob.html.erb
<figure class="attachment attachment--<%= blob.representable? ? "preview" : "file" %> attachment--<%= blob.filename.extension %>">
  <% if blob.representable? %>
    <%= image_tag blob.representation(resize_to_limit: local_assigns[:in_gallery] ? [ 800, 600 ] : [ 1024, 768 ]) %>
  <% end %>

  <figcaption class="attachment__caption">
    <% if caption = blob.try(:caption) %>
      <%= caption %>
    <% else %>
      <span class="attachment__name"><%= blob.filename %></span>
      <span class="attachment__size"><%= number_to_human_size blob.byte_size %></span>
    <% end %>
  </figcaption>
</figure>

app/views/calender/month.erb
<h1 class="m-8 lg:mx-20 text-gray-800 dark:text-white text-3xl font-bold">Calendar</h1>

<div class="mx-8 mb-8 lg:mx-20 lg:mb-20">
    <%= month_calendar { |date| date } %>
    <%= render 'calender/events' %>
</div>

app/views/layouts/_nav.erb
<div class="sticky top-0 z-40 w-full backdrop-blur flex-none transition-colors duration-500 lg:z-50 lg:border-b lg:border-slate-900/10 dark:border-slate-50/[0.06] bg-white supports-backdrop-blur:bg-white/95 dark:bg-slate-900/75">
  <div class="max-w-8xl mx-auto">
    <div class="py-4 border-b border-slate-900/10 lg:px-8 lg:border-0 dark:border-slate-300/10 mx-4 lg:mx-0">
      <div class="relative flex">
        <div class="flex items-center justify-center">
          <%= link_to root_path, { class: 'mr-3 flex-none w-[2.0625rem] overflow-hidden md:w-auto', 'up-follow': '' } do %>
            <span class="sr-only">Lern Mit</span>
            <%= image_tag("logo-lernmit.png", alt: "lernmit", :class => 'w-auto h-6') %>
          <% end %>
        </div>
        <!--
        <div class="ml-3 text-xs leading-5 font-medium text-sky-600 dark:text-sky-400 bg-sky-400/10 rounded-full py-1 px-3 hidden xl:flex items-center hover:bg-sky-400/20">
          <span class="ml-2">A learning platform with superpowers</span>
          <svg width="2" height="2" fill="currentColor" aria-hidden="true" class="ml-2 text-sky-600 dark:text-sky-400/70">
            <circle cx="1" cy="1" r="1"></circle>
          </svg>
        </div>
        -->
        <div class="flex items-center ml-auto">
          <div class="lg:flex hidden">
            <% if signed_in? %>
              <nav class="text-sm leading-6 font-semibold text-slate-700 dark:text-slate-200">
                <ul class="flex space-x-8">
                  <li><%= link_to 'Tasks', tasks_path, class: 'hover:text-sky-500 dark:hover:text-sky-400', 'up-follow': '' %></li>
                  <li><%= link_to 'Calendar', calender_index_url, class: 'hover:text-sky-500 dark:hover:text-sky-400', 'up-follow': '' %></li>
                  <li><%= link_to 'Achievements', achievements_url, class: 'hover:text-sky-500 dark:hover:text-sky-400', 'up-follow': '' %></li>
                </ul>
              </nav>
            <% else %>
              <div class="flex">
                <%= link_to t("auth.sign_in"), new_user_session_path, class: 'py-2.5 px-5 me-2 text-sm font-medium text-gray-100 font-medium text-gray-500 hover:text-sky-500 dark:hover:text-sky-400 focus:outline-none focus:text-gray-900 transition duration-150 ease-in-out', 'up-follow': ''%>
                <%= link_to t('auth.register'), new_user_registration_path, class: 'py-2.5 px-5 me-2 text-sm font-medium text-gray-900 bg-white rounded-lg border border-gray-200 hover:text-sky-500 dark:hover:text-sky-400 dark:bg-gray-800 dark:text-gray-400 dark:border-gray-600 dark:hover:text-white dark:hover:bg-gray-700', 'up-follow': ''%>
              </div>
            <% end %>
          </div>
          <div class="sm:relative flex ml-auto lg:hidden">
            <button @click="dropdown = !dropdown" type="button" class="text-slate-500 w-8 h-8 -my-1 flex items-center justify-center hover:text-slate-600 dark:text-slate-400 dark:hover:text-slate-300">
              <span class="sr-only">Navigation</span>
              <svg width="24" height="24" fill="none" aria-hidden="true">
                <path d="M12 6v.01M12 12v.01M12 18v.01M12 7a1 1 0 1 1 0-2 1 1 0 0 1 0 2Zm0 6a1 1 0 1 1 0-2 1 1 0 0 1 0 2Zm0 6a1 1 0 1 1 0-2 1 1 0 0 1 0 2Z" stroke="currentColor" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round">Sign up</path>
              </svg>
            </button>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

<div x-show="dropdown">
  <div class="fixed z-50 inset-0 sm:ml-auto lg:hidden" role="dialog" tabindex="-1" aria-modal="true">
    <div class="fixed inset-0 bg-black/20 backdrop-blur-sm dark:bg-slate-900/80"></div>
    <div class="fixed top-4 right-4 w-full max-w-xs bg-white rounded-lg shadow-lg p-6 text-base font-semibold text-slate-900 dark:bg-slate-800 dark:text-slate-400 dark:highlight-white/5">
      <button @click="dropdown = !dropdown" type="button" class="absolute top-5 right-5 w-8 h-8 flex items-center justify-center text-slate-500 hover:text-slate-600 dark:text-slate-400 dark:hover:text-slate-300">
        <span class="sr-only">Close navigation</span>
        <svg viewBox="0 0 10 10" class="w-2.5 h-2.5 overflow-visible" aria-hidden="true">
          <path d="M0 0L10 10M10 0L0 10" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round"></path>
        </svg>
      </button>
      <ul class="space-y-6">
        <% if signed_in? %>
          <li><%= link_to 'Tasks', tasks_path, class: 'hover:text-sky-500 dark:hover:text-sky-400', 'up-follow': '', 'up-alias' => task_path('*'), '@click': 'dropdown = !dropdown' %></li>
          <li><%= link_to 'Calendar', calender_index_url, class: 'hover:text-sky-500 dark:hover:text-sky-400', 'up-follow': '', '@click': 'dropdown = !dropdown'%></li>
          <li><%= link_to 'Achievements', achievements_url, class: 'hover:text-sky-500 dark:hover:text-sky-400', 'up-follow': '' , '@click': 'dropdown = !dropdown'%></li></ul>
        <% else %>
          <li><%= link_to t("auth.sign_in"), new_user_session_path, class: 'hover:text-sky-500 dark:hover:text-sky-400', 'up-follow': '', '@click': 'dropdown = !dropdown'%></li>
          <li><%= link_to t('auth.register'), new_user_registration_path, class: 'hover:text-sky-500 dark:hover:text-sky-400', 'up-follow': '', '@click': 'dropdown = !dropdown'%></li>
        <% end %>
    </div>
  </div>
</div>

app/views/simple_calendar/_month_calendar.html.erb
<div class="lg:flex lg:h-full lg:flex-col calendar">
  <header class="flex items-center justify-between rounded-t-md border-b bg-slate-200 dark:bg-gray-800 border-gray-200 dark:border-gray-700 px-6 py-4 lg:flex-none">
    <h1 class="text-base font-semibold leading-6 dark:text-white flex items-center">
      <time datetime="<%= start_date.strftime('%Y-%m') %>"><%= t('date.month_names')[start_date.month] %> <%= start_date.year %></time>
    </h1>
    <div class="flex items-center">
      <div class="relative flex items-center rounded-md bg-white dark:bg-gray-800 shadow-sm md:items-stretch">
        <%= link_to calendar.url_for_previous_view, 'up-target': ".calendar", class: "flex h-9 w-12 items-center justify-center rounded-l-md border-y border-l border-gray-300 dark:border-gray-700 pr-1 text-gray-900 dark:text-gray-200 hover:text-indigo-800 dark:hover:text-indigo-200 focus:relative md:w-9 md:pr-0 md:hover:bg-gray-50 dark:md:hover:bg-gray-700" do %>
          <span class="sr-only">Previous month</span>
          <svg class="h-5 w-5" viewBox="0 0 20 20" fill="currentColor" aria-hidden="true">
            <path fill-rule="evenodd" d="M12.79 5.23a.75.75 0 01-.02 1.06L8.832 10l3.938 3.71a.75.75 0 11-1.04 1.08l-4.5-4.25a.75.75 0 010-1.08l4.5-4.25a.75.75 0 011.06.02z" clip-rule="evenodd"></path>
          </svg>
        <% end %>
        <%= link_to t('simple_calendar.today', default: 'Today'), calendar.url_for_today_view, 'up-target': ".calendar", class: "hidden pt-1.5 border-y border-gray-300 dark:border-gray-700 px-3.5 text-sm font-semibold text-gray-900 dark:text-gray-200 hover:bg-gray-50 dark:hover:bg-gray-700 focus:relative md:block" %>
        <span class="relative -mx-px h-5 w-px bg-gray-300 dark:bg-gray-700 md:hidden"></span>
        <%= link_to calendar.url_for_next_view, 'up-target': ".calendar", class: "flex h-9 w-12 items-center justify-center rounded-r-md border-y border-r border-gray-300 dark:border-gray-700 pl-1 text-gray-900 dark:text-gray-200 hover:text-indigo-800 dark:hover:text-indigo-200 focus:relative md:w-9 md:pl-0 md:hover:bg-gray-50 dark:md:hover:bg-gray-700" do %>
          <span class="sr-only">Next month</span>
          <svg class="h-5 w-5" viewBox="0 0 20 20" fill="currentColor" aria-hidden="true">
            <path fill-rule="evenodd" d="M7.21 14.77a.75.75 0 01.02-1.06L11.168 10 7.23 6.29a.75.75 0 111.04-1.08l4.5 4.25a.75.75 0 010 1.08l-4.5 4.25a.75.75 0 01-1.06-.02z" clip-rule="evenodd"></path>
          </svg>
        <% end %>
      </div>
      <div class="hidden md:ml-4 md:flex md:items-center">
        <div class="relative" x-data="{ open_big: false }">
          <button @click="open_big = !open_big" type="button" class="flex items-center gap-x-1.5 rounded-md bg-white dark:bg-gray-800 px-3 py-2 text-sm font-semibold text-gray-900 dark:text-gray-200 shadow-sm ring-1 ring-inset ring-gray-300 dark:ring-gray-700 hover:bg-gray-50 dark:hover:bg-gray-700" id="menu-button">
            <span class="pr-1"><%= t('simple_calendar.month')%></span>
            <svg class="-mr-1 h-5 w-5 text-gray-400 dark:text-gray-300" viewBox="0 0 20 20" fill="currentColor" aria-hidden="true">
              <path fill-rule="evenodd" d="M5.23 7.21a.75.75 0 011.06.02L10 11.168l3.71-3.938a.75.75 0 111.08 1.04l-4.25 4.5a.75.75 0 01-1.08 0l-4.25-4.5a.75.75 0 01.02-1.06z" clip-rule="evenodd" />
            </svg>
          </button>
          <div x-show="open_big" class="absolute right-0 z-10 mt-3 w-36 origin-top-right overflow-hidden rounded-md bg-white dark:bg-gray-800 shadow-lg ring-1 ring-black ring-opacity-5 dark:ring-opacity-25 focus:outline-none" role="menu" aria-orientation="vertical" aria-labelledby="menu-button" tabindex="-1">
            <div class="py-1" role="none">
              <%= link_to month_calender_index_path, class: "block px-4 pr-3.5 py-2 text-sm #{current_page?(month_calender_index_path) ? 'bg-gray-100 dark:bg-gray-700 text-gray-900 dark:text-gray-100':'text-gray-700 dark:text-gray-300'}", role: 'menuitem', tabindex: '-1', id: 'menu-item-4', 'up-target': '.container' do %><%= t('simple_calendar.month') %><% end %>
              <%= link_to week_calender_index_path, class: "block px-4 pr-3.5 py-2 text-sm #{current_page?(week_calender_index_path) ? 'bg-gray-100 dark:bg-gray-700 text-gray-900 dark:text-gray-100' : 'text-gray-700 dark:text-gray-300'}", role: 'menuitem', tabindex: '-1', id: 'menu-item-5', 'up-target': '.container' do %><%= t('simple_calendar.week') %><% end %>
            </div>
          </div>
        </div>
        <% if can? :create, Task %>
          <div class="ml-6 h-6 w-px bg-gray-300 dark:bg-gray-700"></div>
          <%= link_to new_task_path(event: 'exam'), class: 'flex ml-6 rounded-md bg-indigo-600 px-3 py-2 text-sm font-semibold text-white shadow-sm hover:bg-indigo-500 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-indigo-500', 'up-layer': 'new', 'up-history': 'false', 'up-accept-event': 'task:created', 'up-on-accepted': "up.reload('')" do %>
            <svg class="-ml-1.5 h-5 w-5" viewBox="0 0 20 20" fill="currentColor" aria-hidden="true">
              <path d="M10.75 6.75a.75.75 0 00-1.5 0v2.5h-2.5a.75.75 0 000 1.5h2.5v2.5a.75.75 0 001.5 0v-2.5h2.5a.75.75 0 000-1.5h-2.5v-2.5z"></path>
            </svg>
            Exam
          <% end %>
        <% end %>
      </div>
      <div class="relative ml-6 md:hidden" x-data="{ open_small: false }">
        <button @click="open_small = !open_small" type="button" class="-mx-2 flex items-center rounded-full border border-transparent p-2 text-gray-400 dark:text-gray-300 hover:text-gray-500 dark:hover:text-gray-200" id="menu-0-button">
          <span class="sr-only">Open menu</span>
          <svg class="h-5 w-5" viewBox="0 0 20 20" fill="currentColor" aria-hidden="true">
            <path d="M3 10a1.5 1.5 0 113 0 1.5 1.5 0 01-3 0zM8.5 10a1.5 1.5 0 113 0 1.5 1.5 0 01-3 0zM15.5 8.5a1.5 1.5 0 100 3 1.5 1.5 0 000-3z" />
          </svg>
        </button>
        <div x-show="open_small" class="absolute right-0 z-10 mt-3 w-36 origin-top-right divide-y divide-gray-100 dark:divide-gray-700 overflow-hidden rounded-md bg-white dark:bg-gray-800 shadow-lg ring-1 ring-black ring-opacity-5 dark:ring-opacity-25 focus:outline-none" role="menu" aria-orientation="vertical" aria-labelledby="menu-0-button" tabindex="-1">
          <% if can? :create, Task %>
            <div class="py-1" role="none">
              <%= link_to 'Add event', new_task_path(event: 'exam'), class: 'block px-4 py-2 text-sm text-gray-700 dark:text-gray-300', role: 'menuitem', tabindex: '-1', id: 'menu-item-6', 'up-target': '.container', 'up-layer': 'new', 'up-history': 'false', 'up-accept-event': 'task:created', 'up-on-accepted': "up.reload('.tasks')" %>
            </div>
          <% end %>
          <div class="py-1" role="none">
            <%= link_to t('simple_calendar.today', default: 'Today'), calendar.url_for_today_view, 'up-target': ".calendar", class: "block px-4 py-2 text-sm text-gray-700 dark:text-gray-300", role: 'menuitem', tabindex: '-1', id: 'menu-item-7' %>
          </div>
          <div class="py-1" role="none">
            <%= link_to month_calender_index_path, class: "block px-4 py-2 text-sm  #{current_page?(month_calender_index_path) ? 'bg-gray-100 dark:bg-gray-700 text-gray-900 dark:text-gray-100':'text-gray-700 dark:text-gray-300'}", role: 'menuitem', tabindex: '-1', id: 'menu-item-4', 'up-target': '.container' do %><%= t('simple_calendar.month') %><% end %>
            <%= link_to week_calender_index_path, class: "block px-4 py-2 text-sm #{current_page?(week_calender_index_path) ? 'bg-gray-100 dark:bg-gray-700 text-gray-900 dark:text-gray-100' : 'text-gray-700 dark:text-gray-300'}", role: 'menuitem', tabindex: '-1', id: 'menu-item-5', 'up-target': '.container' do %><%= t('simple_calendar.week') %><% end %>
          </div>
        </div>
      </div>
    </div>
  </header>
  <div class="shadow ring-1 ring-black ring-opacity-5 dark:ring-opacity-25 lg:flex lg:flex-auto lg:flex-col">
    <div class="grid grid-cols-7 gap-px border-b border-gray-300 dark:border-gray-700 bg-gray-200 dark:bg-gray-800 text-center text-xs font-semibold leading-6 text-gray-700 dark:text-gray-300 lg:flex-none">
      <% date_range.slice(0, 7).each do |day| %>
        <div class="flex justify-center bg-white dark:bg-gray-800 py-2">
          <span><%= t('date.abbr_day_names')[day.wday] %></span>
        </div>
      <% end %>
    </div>
  </div>
  <div class="md:block hidden">
    <div class="isolate flex bg-gray-200 dark:bg-gray-800 text-xs leading-6 text-gray-700 dark:text-gray-300 md:flex-auto">
      <div class="hidden w-full md:grid md:grid-cols-7 md:grid-rows-4 md:gap-px">
        <% date_range.each_slice(7) do |week| %>
          <% week.each do |day| %>
            <div class="<%= day.month == start_date.month ? 'relative tile' : 'relative bg-gray-50 dark:bg-gray-700 text-gray-500 dark:text-gray-400' %> px-3 py-2 h-28">
              <time datetime="<%= day.strftime('%Y-%m-%d') %>"><%= day.day %></time>
              <ol class="mt-2">
                <% @load_tasks.each do |task| %>
                  <% if task.due_date.to_date == day.to_date %>
                    <li>
                      <%= link_to task_path(task), class: "group flex", tabindex: "0", 'up-layer': 'new' do %>
                        <p class="flex-auto truncate font-medium text-gray-900 dark:text-white group-hover:text-indigo-600 dark:group-hover:text-indigo-400"><%= task.title %></p>
                        <time datetime="<%= task.due_date %>" class="ml-3 hidden flex-none text-gray-500 group-hover:text-indigo-600 dark:group-hover:text-indigo-400 xl:block"><%= task.due_date.strftime('%I:%M %p') %></time>
                      <% end %>
                    </li>
                  <% end %>
                <% end %>
              </ol>
            </div>
          <% end %>
        <% end %>
      </div>
    </div>
  </div>
  <div class="md:hidden">
    <div class="shadow ring-1 ring-black ring-opacity-5 dark:ring-opacity-25 md:flex md:flex-auto md:flex-col">
      <div class="isolate grid w-full grid-cols-7 grid-rows-5 gap-px">
      <% date_range.each_slice(7) do |week| %>
        <% week.each do |day| %>
            <button type="button" class="flex h-14 flex-col tile px-3 py-2 text-gray-900 dark:text-gray-300 hover:bg-gray-100 dark:hover:bg-gray-700 focus:z-10">
              <time datetime="<%= day.strftime('%Y-%m-%d') %>"><%= day.day %></time>
              <% @load_tasks.each do |task| %>
                <span class="-mx-0.5 mt-auto flex flex-wrap-reverse">
                  <% if task.due_date.to_date == day.to_date %>
                    <span class="mx-0.5 mb-1 h-1.5 w-1.5 rounded-full bg-gray-400 dark:bg-gray-600"></span>
                  <% end %>
                </span>
              <% end %>
            </button>
          <% end %>
        <% end %>
      </div>
    </div>
  </div>
</div>